# Use an official GCC image as a base image
FROM gcc:latest
RUN apt-get update
RUN apt-get install -y netcat-openbsd

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Compile the C code
RUN gcc -o client simple_socket_client.c

# Run the client when the container launches
CMD ["./client"]
